export const DRAW_SETTINGS_KEY = "DRAW_SETTINGS_KEY";

export const SETTINGS_KEY = "SETTINGS";
export const LESSONS_LIST = "LESSONS_LIST";
export const COMPLETED_LESSONS_KEYS = "COMPLETED_LESSONS_KEYS";

export const KANA_STATISTICS = "STATISTICS_KANA";
export const KANA_TRANSLITERATION = "KANA_TRANSLITERATION";
export const SELECTED_KANA = "SELECTED_KANA";

export const IS_WELCOME_PAGE = "IS_WELCOME_PAGE";

export const APP_LANG = "APP_LANG";
export const APP_THEME = "APP_THEME";
export const APP_HAPTIC_ENABLED = "APP_HAPTIC_ENABLED";

export const DEVICE_ID = "NIHONGO_DEVICE_ID";
export const NOTIFICATION_TOKEN = "NIHONGO_NOTIFICATION_TOKEN";
export const FAILED_TO_REQUEST_NOTIFICATION_TOKEN = "FAILED_TO_REQUEST_NOTIFICATION_TOKEN";

export const REVIEW_KEY = "REVIEW_REQUESTED_DATE";

export const PROMOTION_TELEGRAM_KEY = "PROMOTION_TELEGRAM";

export const REMOTE_CONFIG = "REMOTE_CONFIG";

export const API_GATEWAY_LAST_GOOD = "API_GATEWAY_LAST_GOOD";
export const API_GATEWAY_CUSTOM = "API_GATEWAY_CUSTOM";

export const ACCESS_TOKEN = "NIHONGO_ACCESS_TOKEN";
export const REFRESH_TOKEN = "NIHONGO_REFRESH_TOKEN";
